cors:
  originPatterns: http://localhost:8080, http://localhost:3000, http://192.168.1.10:8080, http://192.168.1.8:8080

file:
  upload-dir: C:/ProjetoCursoJava

email:
  subject: "Default Subject"
  message: "Default Message"

spring:
  application:
    name: rest_with_spring_boot_and_java

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_and_java?useTimezone=true&serverTimezone=UTC
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: alefstrogulski@gmail.com
    password: dpxe kzhp avga qyaj
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

springdoc:
  paths-to-match: /person/**
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
