server:
  port: 8888
cors:
  originPatterns: http://localhost:8080, http://localhost:3000
spring:
  application:
    name: rest_with_spring_boot_and_java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
  level:
    com.github.alef_torres: DEBUG
spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true